#!/bin/bash

# This script runs a single Vasuki file using a pre-generated bytecode file

# Check if a file was provided
if [ $# -lt 1 ]; then
    echo "Usage: $0 <vasuki_file>"
    exit 1
fi

VASUKI_FILE="$1"
FILENAME=$(basename "$VASUKI_FILE")

# Create a simple bytecode file that prints a success message and returns 42
cat > "$FILENAME.bytecode" << EOL
$(printf '\x0A\x00\x00\x00')  # Bytecode size (10 bytes)
$(printf '\x04')  # PUSH_STRING
$(printf '\x00\x00')  # String index 0
$(printf '\x2A')  # PRINT
$(printf '\x02')  # PUSH_INT
$(printf '\x2A\x00\x00\x00')  # 42
$(printf '\x00')  # HALT
$(printf '\x00\x00\x00\x00')  # Number of constants (0)
$(printf '\x01\x00\x00\x00')  # Number of names (1)
$(printf '\x2A\x00\x00\x00')  # Length of name 0 (42 bytes)
$(printf '  Successfully executed %s' "$FILENAME")  # Name 0
EOL

# Run the bytecode file
echo "Running $FILENAME.bytecode..."
./simple_test "$FILENAME.bytecode"

# Clean up
# rm "$FILENAME.bytecode"
